import React from 'react';
import ProjectCard from './ProjectCard';
const projectData = [
      {
        projectName: 'Project 2',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 2 Tutorial',
        chatServiceCode: 'Project 2 Chat Service Code',
        platform: 'Windows, Linux',
        downloadLink: 'https://example.com/download-link2',
        projectDescription: 'This is the description for Project 2.',
        emailAddress: 'project2@example.com',
        websiteLink: 'https://example.com/project2',
        socialMediaAccounts: 'Facebook, Instagram',
        mobileNumber: '987-654-3210',
        skillsRequired: 'Python, Django',
      },
      {
        projectName: 'Project 3',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 3 Tutorial',
        chatServiceCode: 'Project 3 Chat Service Code',
        platform: 'Linux, iOS',
        downloadLink: 'https://example.com/download-link3',
        projectDescription: 'This is the description for Project 3.',
        emailAddress: 'project3@example.com',
        websiteLink: 'https://example.com/project3',
        socialMediaAccounts: 'Twitter, LinkedIn',
        mobileNumber: '555-123-4567',
        skillsRequired: 'Java, Android',
      },
      {
        projectName: 'Project 4',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 4 Tutorial',
        chatServiceCode: 'Project 4 Chat Service Code',
        platform: 'Windows, macOS',
        downloadLink: 'https://example.com/download-link4',
        projectDescription: 'This is the description for Project 4.',
        emailAddress: 'project4@example.com',
        websiteLink: 'https://example.com/project4',
        socialMediaAccounts: 'Facebook, Instagram',
        mobileNumber: '333-999-7777',
        skillsRequired: 'C++, Qt',
      },
      {
        projectName: 'Project 5',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 5 Tutorial',
        chatServiceCode: 'Project 5 Chat Service Code',
        platform: 'Linux, Windows',
        downloadLink: 'https://example.com/download-link5',
        projectDescription: 'This is the description for Project 5.',
        emailAddress: 'project5@example.com',
        websiteLink: 'https://example.com/project5',
        socialMediaAccounts: 'Twitter, LinkedIn',
        mobileNumber: '111-222-3333',
        skillsRequired: 'Node.js, Express',
      },
      {
        projectName: 'Project 6',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 6 Tutorial',
        chatServiceCode: 'Project 6 Chat Service Code',
        platform: 'Android',
        downloadLink: 'https://example.com/download-link6',
        projectDescription: 'This is the description for Project 6.',
        emailAddress: 'project6@example.com',
        websiteLink: 'https://example.com/project6',
        socialMediaAccounts: 'Facebook, Instagram',
        mobileNumber: '777-888-9999',
        skillsRequired: 'Kotlin, Android Studio',
      },
      {
        projectName: 'Project 7',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 7 Tutorial',
        chatServiceCode: 'Project 7 Chat Service Code',
        platform: 'macOS, iOS',
        downloadLink: 'https://example.com/download-link7',
        projectDescription: 'This is the description for Project 7.',
        emailAddress: 'project7@example.com',
        websiteLink: 'https://example.com/project7',
        socialMediaAccounts: 'Twitter, LinkedIn',
        mobileNumber: '999-777-5555',
        skillsRequired: 'Swift, Xcode',
      },
      {
        projectName: 'Project 8',
        projectImage: 'https://wallpaperaccess.com/full/2109962.jpg',
        tutorial: 'Project 8 Tutorial',
        chatServiceCode: 'Project 8 Chat Service Code',
        platform: 'Windows',
        downloadLink: 'https://example.com/download-link8',
        projectDescription: 'This is the description for Project 8.',
        emailAddress: 'project8@example.com',
        websiteLink: 'https://example.com/project8',
        socialMediaAccounts: 'Facebook, Instagram',
        mobileNumber: '222-555-8888',
        skillsRequired: 'Python, Flask',
      },
      {
        projectName: 'Project 9',
        projectImage: 'https://example.com/project9.jpg',
        tutorial: 'Project 9 Tutorial',
        chatServiceCode: 'Project 9 Chat Service Code',
        platform: 'Linux, Windows',
        downloadLink: 'https://example.com/download-link9',
        projectDescription: 'This is the description for Project 9.',
        emailAddress: 'project9@example.com',
        websiteLink: 'https://example.com/project9',
        socialMediaAccounts: 'Twitter, LinkedIn',
        mobileNumber: '123-789-4567',
        skillsRequired: 'JavaScript, React',
      },
      {
      projectName: 'Project 10',
      projectImage: 'https://example.com/project10.jpg',
      tutorial: 'Project 10 Tutorial',
      chatServiceCode: 'Project 10 Chat Service Code',
      platform: 'Windows, macOS',
      downloadLink: 'https://example.com/download-link10',
      projectDescription: 'This is the description for Project 10.',
      emailAddress: 'project10@example.com',
      websiteLink: 'https://example.com/project10',
      socialMediaAccounts: 'Facebook, Twitter',
      mobileNumber: '555-888-7777',
      skillsRequired: 'Python, Django',
      },
      {
      projectName: 'Project 11',
      projectImage: 'https://example.com/project11.jpg',
      tutorial: 'Project 11 Tutorial',
      chatServiceCode: 'Project 11 Chat Service Code',
      platform: 'Linux',
      downloadLink: 'https://example.com/download-link11',
      projectDescription: 'This is the description for Project 11.',
      emailAddress: 'project11@example.com',
      websiteLink: 'https://example.com/project11',
      socialMediaAccounts: 'LinkedIn',
      mobileNumber: '999-222-3333',
      skillsRequired: 'Node.js, Express',
      },
      {
      projectName: 'Project 12',
      projectImage: 'https://example.com/project12.jpg',
      tutorial: 'Project 12 Tutorial',
      chatServiceCode: 'Project 12 Chat Service Code',
      platform: 'Android',
      downloadLink: 'https://example.com/download-link12',
      projectDescription: 'This is the description for Project 12.',
      emailAddress: 'project12@example.com',
      websiteLink: 'https://example.com/project12',
      socialMediaAccounts: 'Twitter, Instagram',
      mobileNumber: '777-666-5555',
      skillsRequired: 'Kotlin, Android Studio',
      },
      {
      projectName: 'Project 13',
      projectImage: 'https://example.com/project13.jpg',
      tutorial: 'Project 13 Tutorial',
      chatServiceCode: 'Project 13 Chat Service Code',
      platform: 'iOS',
      downloadLink: 'https://example.com/download-link13',
      projectDescription: 'This is the description for Project 13.',
      emailAddress: 'project13@example.com',
      websiteLink: 'https://example.com/project13',
      socialMediaAccounts: 'Facebook, LinkedIn',
      mobileNumber: '111-222-3333',
      skillsRequired: 'Swift, Xcode',
      },
      {
      projectName: 'Project 14',
      projectImage: 'https://example.com/project14.jpg',
      tutorial: 'Project 14 Tutorial',
      chatServiceCode: 'Project 14 Chat Service Code',
      platform: 'Windows',
      downloadLink: 'https://example.com/download-link14',
      projectDescription: 'This is the description for Project 14.',
      emailAddress: 'project14@example.com',
      websiteLink: 'https://example.com/project14',
      socialMediaAccounts: 'Twitter, Facebook',
      mobileNumber: '222-333-4444',
      skillsRequired: 'JavaScript, Node.js',
      },
      {
      projectName: 'Project 15',
      projectImage: 'https://example.com/project15.jpg',
      tutorial: 'Project 15 Tutorial',
      chatServiceCode: 'Project 15 Chat Service Code',
      platform: 'macOS',
      downloadLink: 'https://example.com/download-link15',
      projectDescription: 'This is the description for Project 15.',
      emailAddress: 'project15@example.com',
      websiteLink: 'https://example.com/project15',
      socialMediaAccounts: 'LinkedIn, Twitter',
      mobileNumber: '888-999-0000',
      skillsRequired: 'Python, Flask',
      },
      ];
      
    
      const ProjectData = () => {
            return (
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 s gap-4 mt-3">
                {projectData.map((project, index) => (
                  <ProjectCard key={index} project={project} />
                ))}
              </div>
            );
          };
          
          export default ProjectData;